# Generated by Django 3.2.22 on 2024-08-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_profile_mode'),
        ('projects', '0002_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to='teams.Member'),
        ),
    ]
