# Generated by Django 3.2.22 on 2024-08-03 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='stride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='projects.stride'),
        ),
        migrations.AlterField(
            model_name='stride',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strides', to='projects.project'),
        ),
    ]
