# Generated by Django 3.2.22 on 2024-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.IntegerField(default=1),
        ),
    ]
