# Generated by Django 3.2.22 on 2024-08-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_profile_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
